### ISSUE TITLE
新版本的 无法使用 

### ISSUE THREAD

**Issue by cxy-yanggod** [qtgolang/SunnyNetTools#3]
第一次安装证书操作之后 可以使用 权限都有给 正常 
重启计算机之后  已经到1007版本了 还是用不了 
![Uploading 微信截图_20231221223040.png…]()

**Comment by cxy-yanggod** [comment]
![Uploading 微信截图_20231221223040.png…]()

**Comment by qtgolang** [comment]
图片无法查看

**Comment by cxy-yanggod** [comment]
> 图片无法查看

![微信截图_20231221223040](https://github.com/qtgolang/SunnyNetTools/assets/111846227/aa784eaa-2957-446f-863b-3b237298027a)

**Comment by cxy-yanggod** [comment]
> 图片无法查看
图片已添加

**Comment by qtgolang** [comment]
检查一下设置，如果还是没有搞定。加群：545120699 联系我远程看看

**Comment by cxy-yanggod** [comment]
> 545120699

已加群

**Comment by cxy-yanggod** [comment]
已解决，谢谢

**Comment by qtgolang** [comment]
![QQ截图20231221225002](https://github.com/qtgolang/SunnyNetTools/assets/57537577/56b6972e-5394-4bc6-af98-a016d17c7697)
点击这里取消过滤规则，每一列都可以设置，检查每一列的规则
