### ISSUE TITLE
右击菜单会自动消失我刚刚用最新代码编译的

### ISSUE THREAD

**Issue by Pengzf** [qtgolang/SunnyNetTools#4]
![动画](https://github.com/qtgolang/SunnyNetTools/assets/22533957/ea1ae72e-8dae-4f3c-9ca4-456bac4be22c)
右击菜单会自动消失我刚刚用最新代码编译的

**Comment by qtgolang** [comment]
这是由于Ag-grid 的BUG，应该算是BUG，当表格更新时，会隐藏右键菜单，解决办法
找到文件 `frontend\node_modules\@ag-grid-community\core\dist\esm\es6\widgets\popupService.mjs`
搜索`                if (elementNotInDom) {
                    params.hidePopup();
                    return;
                }`
替换为`                if (elementNotInDom) {
                    //params.hidePopup();
                    return;
                }`
删除目录 `frontend\dist`
删除目录 `frontend\node_modules\.vite`
再次执行 `wails dev`

**Comment by Pengzf** [comment]
非常感谢大佬指点，刚刚测试完美解决
