### ISSUE TITLE
【疑问】手机上的app请求可以抓到吗？

### ISSUE THREAD

**Issue by shenjo** [qtgolang/SunnyNetTools#8]
电脑浏览器上的请求都能抓到了。我想抓下手机的请求，我做了如下设置

1. 手机和电脑连同一个wifi
2. 手机中的wifi代理设置 服务器填了电脑的ip地址，端口填写了 sunnynet的端口（2024）

结果发现手机连不上网了。是我设置的问题还是sunnynet不支持？

**Comment by qtgolang** [comment]
当然支持，请检查手机和电脑是否在同一局域网，并且检查电脑防火墙，软件中都有教程的

**Comment by shenjo** [comment]
软件内看到了，是我手机里没装证书，谢谢大佬
